name: Date Library Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ACS-3310-JS-DATE-LIBRARY/
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js and test
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

